# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            0x44.cc
tagline:          'InfoSec, Reversing, and more'
description:      'InfoSec, Reverse Engineering, and more (soon&trade;)'
url:              https://0x44.cc
#baseurl:          '/hydeout'

author:
  name:           'Sami ALAOUI KENDIL'
  url:            https://linkedin.com/thedroidgeek

github_username:      thedroidgeek
linkedin_username:    thedroidgeek

disqus:
  shortname:     0x41-cf

paginate:           3
paginate_path:    '/page/:num'
excerpt_max_length: 300

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-timeago

# Simplify category URLs
defaults:
    - scope:
        path: category
        type: pages
      values:
        permalink: /:basename/

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

extlinks:
  attributes: {rel: noopener noreferrer, target: _blank}
